/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DesignMyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface DesignWidget {
        "username": string;
    }
}
export interface DesignWidgetCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDesignWidgetElement;
}
declare global {
    interface HTMLDesignMyComponentElement extends Components.DesignMyComponent, HTMLStencilElement {
    }
    var HTMLDesignMyComponentElement: {
        prototype: HTMLDesignMyComponentElement;
        new (): HTMLDesignMyComponentElement;
    };
    interface HTMLDesignWidgetElement extends Components.DesignWidget, HTMLStencilElement {
    }
    var HTMLDesignWidgetElement: {
        prototype: HTMLDesignWidgetElement;
        new (): HTMLDesignWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "design-my-component": HTMLDesignMyComponentElement;
        "design-widget": HTMLDesignWidgetElement;
    }
}
declare namespace LocalJSX {
    interface DesignMyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface DesignWidget {
        "onChangeUsername"?: (event: DesignWidgetCustomEvent<string>) => void;
        "username"?: string;
    }
    interface IntrinsicElements {
        "design-my-component": DesignMyComponent;
        "design-widget": DesignWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "design-my-component": LocalJSX.DesignMyComponent & JSXBase.HTMLAttributes<HTMLDesignMyComponentElement>;
            "design-widget": LocalJSX.DesignWidget & JSXBase.HTMLAttributes<HTMLDesignWidgetElement>;
        }
    }
}
