/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MarketComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMarketComponentElement extends Components.MarketComponent, HTMLStencilElement {
    }
    var HTMLMarketComponentElement: {
        prototype: HTMLMarketComponentElement;
        new (): HTMLMarketComponentElement;
    };
    interface HTMLElementTagNameMap {
        "market-component": HTMLMarketComponentElement;
    }
}
declare namespace LocalJSX {
    interface MarketComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "market-component": MarketComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "market-component": LocalJSX.MarketComponent & JSXBase.HTMLAttributes<HTMLMarketComponentElement>;
        }
    }
}
